### ISSUE TITLE
Other items got a vessel assignment even if I only assigned 1 Item for a schedule

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#552] opened 2015-04-06 03:30 UTC
**Steps to Replicate**
1. Log in as admin
2. Go to freight planning
3. Add a booking record, similar to the record on picture 50B,
On the items, add multiple item records with different data.
4. Go to freight planning
5. Look for the added record
6. Click on the = icon
7. Click on 1 item check box only, then click the = icon to set the vessel
8. If there are no vessel available, add two
9. Click the assign button ->
10. The page will display assignment of 1 item to 1 vessel
11. Save the record
12. On the Freight planning record page, all the containers will have the same vessel that was assigned on the 1 item only

**Actual Result**
Other items got a vessel assignment even if I only assigned 1 ITEM for a schedule

![50](https://cloud.githubusercontent.com/assets/9795882/7000241/eb710342-dc4f-11e4-87c0-8bfe431ba9cf.png)

**Expected Result**
Since there were only 1 item that got a vessel assignment, all the other items should not have vessel schedule assignment

**Comment by JMXPSX** [comment] 2015-04-16 11:03
This is working as intended.

We had decided to have one shipping vessel / voyage number per booking thus when setting either single or multiple order item, it will apply to other remaining order items as well.

**Comment by barbacenasmc** [comment] 2015-06-02 06:38
This is for clarification if will also be added for version 2 like issue #612

**Comment by JMXPSX** [comment] 2015-06-02 07:30
Assignment of Vessel Schedule per booking was the final decision to handle each booking efficiently as there are too many possible use case scenario that will be involved.

Multiple Vessel Schedule will be implemented in detail on version 2 depending on the design documents that will be agreed upon by both the Client and developers if it is feasible.

**Comment by egmsantos** [comment] 2015-08-07 02:54
Fixed and verified. For closure

![eios_626](https://cloud.githubusercontent.com/assets/12589800/9127795/9b1863d2-3cf2-11e5-8a2d-98dd9f9ecb12.png)

**Closed** 2015-08-10 02:00 UTC
Labels: For Version 2, Medium
