### ISSUE TITLE
Status on booking page is different from the ARRIVED status that was set from the ongoing booking list

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#553] opened 2015-04-06 03:36 UTC
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a booking record, approve it
4. Go to dispatch planning
5. Add a vendor
6. Go to shipping monitoring
7. Set the status of the booking to ARRIVED
8. Go back to booking
9. The status is still ONGOING

**Actual Result**
Status on booking page is different from the ARRIVED status that was set from the ongoing booking list

![52](https://cloud.githubusercontent.com/assets/9795882/7000297/f4e4aa22-dc50-11e4-9d39-8f1e63168136.png)

**Expected Result**
The status for a booking record should be consistent for all the modules

**Comment by knarceo** [comment] 2015-04-21 03:24
Fixed on next push.

**Comment by JMXPSX** [comment] 2015-04-21 06:45
Working as intended. Order Items has their own different Status compared to the main overall booking. During, while, after planning and also in shipment monitoring. The Booking status remains On-Going while the Order Items changes depending on the current status that the user set for them in EIOS.

**Closed** 2015-06-01 05:42 UTC
Labels: Medium
