### ISSUE TITLE
Add Consumer Contact:The page still enables the user to go to add consignee form but will not allow the user to add another consignee contact person to the consignee

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#511] opened 2015-03-27 08:20 UTC
Steps to replicate:
1. Login as admin
2. Go to customer 
3. Click customer details
4. Go to consignee
5. If there are no consignee, add one
6. Go to the consignee details
7. Add contact person
8.  Fill up valid data and save it
9. Upon saving you will be redirected to the consignee page
10. There is a button contact person
11. Click on it
12. You will be redirected to the add consignee contact person
13. Fill out the form
14. Click save
15. The page will say "Cannot add an additional Contact Person for this Consignee"

Actual result: The page still enables the user to go to add consignee form but will not allow the user to add another consignee contact person to the consignee

Expected result: The page will no longer display the button or the link because the system will no longer allow the user to add another consignee.
Also trap the direct URL access.

![6](https://cloud.githubusercontent.com/assets/7791554/6864510/38b11f58-d49d-11e4-94e3-b65598f35838.png)

**Comment by JMXPSX** [comment] 2015-03-27 10:25
Consignee may only have one contact person as per Sir Jan

**Comment by JMXPSX** [comment] 2015-03-30 08:18
Working as intended

**Comment by barbacenasmc** [comment] 2015-03-31 03:57
Hi team, then if this is the case, the "New Contact Person" should no longer be available once the user added a contact person for the consignee. As a result, add contact person should not also be available on the add booking form if the selected consignee already has a contact person. As of now, I was able to check that through the add booking form, I can add more than 1 contact person for the consignee. 

![image](https://cloud.githubusercontent.com/assets/7791554/6912082/075ec74a-d79d-11e4-96c7-394b78f6462d.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6912089/1801464a-d79d-11e4-9b56-e2ac1bea3e4a.png)

**Comment by knarceo** [comment] 2015-04-08 08:09
Issue was fixed in this commit number a5d185a793e823500113ac7b5dc7c7524b8843c5

**Comment by Leirum** [comment] 2015-04-13 10:36
Issue can still be replicated. 

![screen shot 2015-04-13 at 6 34 42 pm](https://cloud.githubusercontent.com/assets/9795882/7114014/fbe40ab4-e20b-11e4-9f13-4e1ed01fd2d4.png)

**Comment by JMXPSX** [comment] 2015-04-16 11:32
Issue has now been fixed. Please see latest build

**Comment by Leirum** [comment] 2015-05-06 05:09
Issue can still be replicated on http://eios.solutionsresource.com

**Comment by barbacenasmc** [comment] 2015-06-02 06:43
Hi team, any update on this? Thanks.

**Comment by barbacenasmc** [comment] 2015-06-05 01:48
Issue can still be replicated:
![screenshot-46](https://cloud.githubusercontent.com/assets/7791554/7997960/f029398a-0b67-11e5-92c1-f2bbbbe35494.png)
![screenshot-47](https://cloud.githubusercontent.com/assets/7791554/7997963/0131bf18-0b68-11e5-9ad0-82c301a00deb.png)

**Comment by egmsantos** [comment] 2015-08-07 02:59
Issue fixed and verified. For closure
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9127856/5e9cf2e6-3cf3-11e5-8ae0-7b5979ddf922.png)

**Closed** 2015-08-10 02:00 UTC
Labels: Medium
