### ISSUE TITLE
Dispatch Plan Edit Vendor: All fields in Dispatch Plan Origin were Disabled.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#419] opened 2015-02-05 08:44 UTC
**Steps to replicate**
1. Log in as Admin
2. Navigate to Booking Module.
3. Create New Booking
4. Assign the Service Mode as Door to Pier.
5. Navigate to Operations --> Freight Plan
6. Click the Set Vessel Schedule Icon in the Action Panel of the Freight Plan List of the Created New Booking.
7. Select Vendor then Click Set Vendor
8. Fill out all fields.
9. When the status was set to Planning 2, navigate to Dispatch Plan Module
10. Select the Vendor and click the Set Vendor button.
11. Fill out all fields in Dispatch Plan: Origin.
12. Select the vendor with an ongoing status.
13. Click the Edit Vendor button.

**Actual Result**
- All fields in Dispatch Plan: Origin were disabled
- There are no values displayed in the fields of Dispatch Plan: Origin.

**Expected Result**
- All fields should be enabled for the editing of vendor information.
- Last saved information should be retrieved in each field in Dispatch Plan: Origin.

![dispatch plan edit vendor](https://cloud.githubusercontent.com/assets/9795882/6057135/7552f414-ad55-11e4-8445-3b6911e2970d.png)

**Comment by knarceo** [comment] 2015-02-11 10:09
Fixed on next push on cloud.

**Comment by knarceo** [comment] 2015-02-12 01:51
Fixed this issue, but instead of retrieving values, I showed the available current vendors that exist for that item. Because there is a limitation that, we can't retrieve values of such item because its only limited for 1 item selection only, there will be conflict if we retrieve the values of bulk or many items selected.

**Comment by barbacenasmc** [comment] 2015-02-13 02:48
Duplicate of #420. Closing this issue.

**Closed by barbacenasmc** 2015-02-13 02:48 UTC
Labels: Medium
